version: "3.9"
services:
  service-registry:
    build: ./services/service-registry
    ports:
      - "8761:8761"

  claims-service:
    build: ./services/claims-service
    ports:
      - "8081:8081"

  identity-service:
    build: ./services/identity-service
    ports:
      - "8082:8082"

  analytics-service:
    build: ./services/analytics-service
    ports:
      - "8083:8083"

  notification-service:
    build: ./services/notification-service
    ports:
      - "8084:8084"

  api-gateway:
    build: ./services/api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - claims-service
      - identity-service
      - analytics-service
      - notification-service
