import { useState, useEffect } from 'react'
import { dashboardAPI } from '../api'

export default function Reports() {
  const [reports, setReports] = useState([])
  const [loading, setLoading] = useState(true)
  const [creating, setCreating] = useState(false)
  const [selectedReport, setSelectedReport] = useState(null)
  const [formData, setFormData] = useState({
    reportName: '',
    reportType: 'KPI',
    generatedBy: 'UI User',
    periodStart: '',
    periodEnd: '',
    scope: ''
  })

  useEffect(() => {
    loadReports()
  }, [])

  const loadReports = async () => {
    try {
      const response = await dashboardAPI.getAllReports()
      setReports(response.data)
    } catch (error) {
      console.error('Error loading reports:', error)
    } finally {
      setLoading(false)
    }
  }

  const handleGenerateReport = async (event) => {
    event.preventDefault()
    try {
      await dashboardAPI.generateReport(formData)
      setCreating(false)
      setFormData({
        reportName: '',
        reportType: 'KPI',
        generatedBy: 'UI User',
        periodStart: '',
        periodEnd: '',
        scope: ''
      })
      await loadReports()
    } catch (error) {
      console.error('Error generating report:', error)
    }
  }

  const handleViewReport = async (id) => {
    try {
      const response = await dashboardAPI.getReportById(id)
      setSelectedReport(response.data)
    } catch (error) {
      console.error('Error loading report:', error)
    }
  }

  if (loading) return <div className="loading">Loading...</div>

  return (
    <div>
      <div className="page-header">
        <h2>Analytics Reports</h2>
        <p>Generate and view comprehensive analytics reports</p>
      </div>

      <div className="card">
        <div className="card-header">
          <h3 className="card-title">Available Reports</h3>
          <button className="btn btn-primary" onClick={() => setCreating((value) => !value)}>
            {creating ? 'Cancel' : 'Generate New Report'}
          </button>
        </div>

        {creating && (
          <form onSubmit={handleGenerateReport} style={{ padding: '16px 24px', borderBottom: '1px solid #e2e8f0' }}>
            <div className="dashboard-grid" style={{ marginBottom: 12 }}>
              <div>
                <label>Name</label>
                <input
                  required
                  value={formData.reportName}
                  onChange={(event) => setFormData((prev) => ({ ...prev, reportName: event.target.value }))}
                />
              </div>
              <div>
                <label>Type</label>
                <input
                  required
                  value={formData.reportType}
                  onChange={(event) => setFormData((prev) => ({ ...prev, reportType: event.target.value }))}
                />
              </div>
              <div>
                <label>Generated By</label>
                <input
                  value={formData.generatedBy}
                  onChange={(event) => setFormData((prev) => ({ ...prev, generatedBy: event.target.value }))}
                />
              </div>
              <div>
                <label>Period Start</label>
                <input
                  value={formData.periodStart}
                  onChange={(event) => setFormData((prev) => ({ ...prev, periodStart: event.target.value }))}
                />
              </div>
              <div>
                <label>Period End</label>
                <input
                  value={formData.periodEnd}
                  onChange={(event) => setFormData((prev) => ({ ...prev, periodEnd: event.target.value }))}
                />
              </div>
              <div>
                <label>Scope</label>
                <input
                  value={formData.scope}
                  onChange={(event) => setFormData((prev) => ({ ...prev, scope: event.target.value }))}
                />
              </div>
            </div>
            <button className="btn btn-primary" type="submit">Generate</button>
          </form>
        )}
        <div className="table-container">
          <table>
            <thead>
              <tr>
                <th>Report ID</th>
                <th>Name</th>
                <th>Type</th>
                <th>Generated Date</th>
                <th>Generated By</th>
                <th>Status</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {reports.length > 0 ? (
                reports.map((report) => (
                  <tr key={report.reportId}>
                    <td>{report.reportId}</td>
                    <td>{report.reportName}</td>
                    <td>
                      <span className="badge info">{report.reportType}</span>
                    </td>
                    <td>{new Date(report.generatedDate).toLocaleDateString()}</td>
                    <td>{report.generatedBy || 'System'}</td>
                    <td>
                      <span className={`badge ${
                        report.status === 'Generated' ? 'success' :
                        report.status === 'Scheduled' ? 'warning' : 'danger'
                      }`}>
                        {report.status}
                      </span>
                    </td>
                    <td>
                      <button
                        className="btn btn-secondary"
                        style={{ fontSize: '12px', padding: '6px 12px' }}
                        onClick={() => handleViewReport(report.reportId)}
                      >
                        View
                      </button>
                    </td>
                  </tr>
                ))
              ) : (
                <tr>
                  <td colSpan="7" style={{ textAlign: 'center' }}>
                    No reports available. Generate your first report to get started.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>

      {selectedReport && (
        <div className="card">
          <div className="card-header">
            <h3 className="card-title">Selected Report: {selectedReport.reportName}</h3>
          </div>
          <div style={{ padding: '16px 24px' }}>
            <p><strong>Type:</strong> {selectedReport.reportType}</p>
            <p><strong>Status:</strong> {selectedReport.status}</p>
            <p><strong>Scope:</strong> {selectedReport.scope || '-'}</p>
            <p><strong>Metrics JSON:</strong> {selectedReport.metricsJson || '-'}</p>
          </div>
        </div>
      )}

      <div className="dashboard-grid">
        <div className="stat-card blue">
          <div className="stat-label">Total Reports</div>
          <div className="stat-value">{reports.length}</div>
        </div>
        <div className="stat-card green">
          <div className="stat-label">Generated</div>
          <div className="stat-value">{reports.filter(r => r.status === 'Generated').length}</div>
        </div>
        <div className="stat-card yellow">
          <div className="stat-label">Scheduled</div>
          <div className="stat-value">{reports.filter(r => r.status === 'Scheduled').length}</div>
        </div>
      </div>
    </div>
  )
}
