spring.application.name=api-gateway
server.port=8080

management.endpoints.web.exposure.include=health,info

services.claims.base-url=http://localhost:8081
services.identity.base-url=http://localhost:8082
services.analytics.base-url=http://localhost:8083
services.notification.base-url=http://localhost:8084
